voices = {
    "Anna": {
        "api": "Naver",
        "apiName": "danna",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en",
    },
    "Clara": {
        "api": "Naver",
        "apiName": "clara",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en",
    },
    "Matt": {
        "api": "Naver",
        "apiName": "matt",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en",
    },
    "Joey": {
        "api": "Naver",
        "apiName": "djoey",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en",
    },
    "Jose": {
        "api": "Naver",
        "apiName": "jose",
        "languageName": "Spanish",
        "gender": "Male",
        "languageCode": "es",
    },
    "Carmen": {
        "api": "Naver",
        "apiName": "carmen",
        "languageName": "Spanish",
        "gender": "Female",
        "languageCode": "es",
    },
    "Shinji": {
        "api": "Naver",
        "apiName": "shinji",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Tomoko": {
        "api": "Naver",
        "apiName": "ntomoko",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Naomi": {
        "api": "Naver",
        "apiName": "nnaomi",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Hina": {
        "api": "Naver",
        "apiName": "dnaomi_joyful",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Yua": {
        "api": "Naver",
        "apiName": "dnaomi_formal",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Sayuri": {
        "api": "Naver",
        "apiName": "nsayuri",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Riko": {
        "api": "Naver",
        "apiName": "driko",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Eriko": {
        "api": "Naver",
        "apiName": "deriko",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Meimei": {
        "api": "Naver",
        "apiName": "meimei",
        "languageName": "Chinese",
        "gender": "Female",
        "languageCode": "zh",
    },
    "Liangliang": {
        "api": "Naver",
        "apiName": "liangliang",
        "languageName": "Chinese",
        "gender": "Male",
        "languageCode": "zh",
    },
    "Chiahua": {
        "api": "Naver",
        "apiName": "chiahua",
        "languageName": "Taiwanese",
        "gender": "Female",
        "languageCode": "zh",
    },
    "Kuanlin": {
        "api": "Naver",
        "apiName": "kuanlin",
        "languageName": "Taiwanese",
        "gender": "Male",
        "languageCode": "zh",
    },
    "Hajime": {
        "api": "Naver",
        "apiName": "dhajime",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Daiki": {
        "api": "Naver",
        "apiName": "ddaiki",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Ayumu": {
        "api": "Naver",
        "apiName": "dayumu",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Mio": {
        "api": "Naver",
        "apiName": "dmio",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Nara": {
        "api": "Naver",
        "apiName": "nara",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Mijin": {
        "api": "Naver",
        "apiName": "mijin",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Jinho": {
        "api": "Naver",
        "apiName": "njinho",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Minsang": {
        "api": "Naver",
        "apiName": "nminsang",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Hajoon": {
        "api": "Naver",
        "apiName": "nhajun",
        "languageName": "Korean",
        "gender": "Boy",
        "languageCode": "ko",
    },
    "Dain": {
        "api": "Naver",
        "apiName": "ndain",
        "languageName": "Korean",
        "gender": "Girl",
        "languageCode": "ko",
    },
    "Jiyoon": {
        "api": "Naver",
        "apiName": "njiyun",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sujin": {
        "api": "Naver",
        "apiName": "nsujin",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Shinwoo": {
        "api": "Naver",
        "apiName": "nsinu",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Jihoon": {
        "api": "Naver",
        "apiName": "njihun",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Koeun": {
        "api": "Naver",
        "apiName": "ngoeun",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Eunyoung": {
        "api": "Naver",
        "apiName": "neunyoung",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sunkyung": {
        "api": "Naver",
        "apiName": "nsunkyung",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Yujin": {
        "api": "Naver",
        "apiName": "nyujin",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Taejin": {
        "api": "Naver",
        "apiName": "ntaejin",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Youngil": {
        "api": "Naver",
        "apiName": "nyoungil",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Seungpyo": {
        "api": "Naver",
        "apiName": "nseungpyo",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Wontak": {
        "api": "Naver",
        "apiName": "nwontak",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Ara": {
        "api": "Naver",
        "apiName": "dara_ang",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sunhee": {
        "api": "Naver",
        "apiName": "nsunhee",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Minseo": {
        "api": "Naver",
        "apiName": "nminseo",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Jiwon": {
        "api": "Naver",
        "apiName": "njiwon",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Bora": {
        "api": "Naver",
        "apiName": "nbora",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Jonghyun": {
        "api": "Naver",
        "apiName": "njonghyun",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Joonyoung": {
        "api": "Naver",
        "apiName": "njoonyoung",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Jaewook": {
        "api": "Naver",
        "apiName": "njaewook",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Hyeri": {
        "api": "Naver",
        "apiName": "nes_c_hyeri",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sohyun": {
        "api": "Naver",
        "apiName": "nes_c_sohyun",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Mikyung": {
        "api": "Naver",
        "apiName": "nes_c_mikyung",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Kihyo": {
        "api": "Naver",
        "apiName": "nes_c_kihyo",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Sally": {
        "api": "MaryTTS",
        "apiName": "cmu-slt-hsmm",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Henry": {
        "api": "MaryTTS",
        "apiName": "cmu-rms-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Mark": {
        "api": "MaryTTS",
        "apiName": "cmu-bdl-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Pierre": {
        "api": "MaryTTS",
        "apiName": "upmc-pierre-hsmm",
        "languageName": "French",
        "gender": "Male",
        "languageCode": "fr-FR",
    },
    "Jessica": {
        "api": "MaryTTS",
        "apiName": "upmc-jessica-hsmm",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Lucia": {
        "api": "MaryTTS",
        "apiName": "istc-lucia-hsmm",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it",
    },
    "Hans": {
        "api": "MaryTTS",
        "apiName": "dfki-pavoque-neutral-hsmm",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de-DE",
    },
    "Roberto": {
        "api": "MaryTTS",
        "apiName": "mivoq-roberto-hsmm",
        "languageName": "Itallian",
        "gender": "Male",
        "languageCode": "it",
    },
    "Patrizia": {
        "api": "MaryTTS",
        "apiName": "mivoq-patrizia-hsmm",
        "languageName": "Itallian",
        "gender": "Female",
        "languageCode": "it",
    },
    "Piero": {
        "api": "MaryTTS",
        "apiName": "istc-piero-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Camila": {
        "api": "MaryTTS",
        "apiName": "enst-camilla-hsmm",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr",
    },
    "Stefan": {
        "api": "MaryTTS",
        "apiName": "dfki-stefan-hsmm",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de",
    },
    "Mario": {
        "api": "MaryTTS",
        "apiName": "istc-speaker_internazionale-hsmm",
        "languageName": "Italian",
        "gender": "Male",
        "languageCode": "it",
    },
    "Shane": {
        "api": "MaryTTS",
        "apiName": "cmu-jmk-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Aileen": {
        "api": "MaryTTS",
        "apiName": "cmu-clb-hsmm",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Sophia": {
        "api": "NanoTTS",
        "apiName": "en-GB",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Isabella": {
        "api": "NanoTTS",
        "apiName": "en-US",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Gisela": {
        "api": "NanoTTS",
        "apiName": "de-DE",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Gabriela": {
        "api": "NanoTTS",
        "apiName": "es-ES",
        "languageName": "Spanish",
        "gender": "Female",
        "languageCode": "es-ES",
    },
    "Coraline": {
        "api": "NanoTTS",
        "apiName": "fr-FR",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Mia": {
        "api": "NanoTTS",
        "apiName": "it-IT",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it-IT",
    },
}
