from .tts_plugins.fifteenai import FifteenAIPlugin
from .tts_plugins.googletranslate import GoogleTranslatePlugin
from .tts_plugins.marytts import MaryTTSPlugin
from .tts_plugins.nanotts import NanoTTSPlugin
from .tts_plugins.naver import NaverPlugin
from .tts_plugins.streamelements import StreamElementsPlugin

voices = {
    "Anna": {
        "api": NaverPlugin,
        "apiName": "danna",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en",
    },
    "Clara": {
        "api": NaverPlugin,
        "apiName": "clara",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en",
    },
    "Matt": {
        "api": NaverPlugin,
        "apiName": "matt",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en",
    },
    "Joey": {
        "api": NaverPlugin,
        "apiName": "djoey",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en",
    },
    "Jose": {
        "api": NaverPlugin,
        "apiName": "jose",
        "languageName": "Spanish",
        "gender": "Male",
        "languageCode": "es",
    },
    "Carmen": {
        "api": NaverPlugin,
        "apiName": "carmen",
        "languageName": "Spanish",
        "gender": "Female",
        "languageCode": "es",
    },
    "Shinji": {
        "api": NaverPlugin,
        "apiName": "shinji",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Tomoko": {
        "api": NaverPlugin,
        "apiName": "ntomoko",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Naomi": {
        "api": NaverPlugin,
        "apiName": "nnaomi",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Hina": {
        "api": NaverPlugin,
        "apiName": "dnaomi_joyful",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Yua": {
        "api": NaverPlugin,
        "apiName": "dnaomi_formal",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Sayuri": {
        "api": NaverPlugin,
        "apiName": "nsayuri",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Riko": {
        "api": NaverPlugin,
        "apiName": "driko",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Eriko": {
        "api": NaverPlugin,
        "apiName": "deriko",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Meimei": {
        "api": NaverPlugin,
        "apiName": "meimei",
        "languageName": "Chinese",
        "gender": "Female",
        "languageCode": "zh",
    },
    "Liangliang": {
        "api": NaverPlugin,
        "apiName": "liangliang",
        "languageName": "Chinese",
        "gender": "Male",
        "languageCode": "zh",
    },
    "Chiahua": {
        "api": NaverPlugin,
        "apiName": "chiahua",
        "languageName": "Taiwanese",
        "gender": "Female",
        "languageCode": "zh",
    },
    "Kuanlin": {
        "api": NaverPlugin,
        "apiName": "kuanlin",
        "languageName": "Taiwanese",
        "gender": "Male",
        "languageCode": "zh",
    },
    "Hajime": {
        "api": NaverPlugin,
        "apiName": "dhajime",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Daiki": {
        "api": NaverPlugin,
        "apiName": "ddaiki",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Ayumu": {
        "api": NaverPlugin,
        "apiName": "dayumu",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja",
    },
    "Mio": {
        "api": NaverPlugin,
        "apiName": "dmio",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Nara": {
        "api": NaverPlugin,
        "apiName": "nara",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Mijin": {
        "api": NaverPlugin,
        "apiName": "mijin",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Jinho": {
        "api": NaverPlugin,
        "apiName": "njinho",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Minsang": {
        "api": NaverPlugin,
        "apiName": "nminsang",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Hajoon": {
        "api": NaverPlugin,
        "apiName": "nhajun",
        "languageName": "Korean",
        "gender": "Boy",
        "languageCode": "ko",
    },
    "Dain": {
        "api": NaverPlugin,
        "apiName": "ndain",
        "languageName": "Korean",
        "gender": "Girl",
        "languageCode": "ko",
    },
    "Jiyoon": {
        "api": NaverPlugin,
        "apiName": "njiyun",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sujin": {
        "api": NaverPlugin,
        "apiName": "nsujin",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Shinwoo": {
        "api": NaverPlugin,
        "apiName": "nsinu",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Jihoon": {
        "api": NaverPlugin,
        "apiName": "njihun",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Koeun": {
        "api": NaverPlugin,
        "apiName": "ngoeun",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Eunyoung": {
        "api": NaverPlugin,
        "apiName": "neunyoung",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sunkyung": {
        "api": NaverPlugin,
        "apiName": "nsunkyung",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Yujin": {
        "api": NaverPlugin,
        "apiName": "nyujin",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Taejin": {
        "api": NaverPlugin,
        "apiName": "ntaejin",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Youngil": {
        "api": NaverPlugin,
        "apiName": "nyoungil",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Seungpyo": {
        "api": NaverPlugin,
        "apiName": "nseungpyo",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Wontak": {
        "api": NaverPlugin,
        "apiName": "nwontak",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Ara": {
        "api": NaverPlugin,
        "apiName": "dara_ang",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sunhee": {
        "api": NaverPlugin,
        "apiName": "nsunhee",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Minseo": {
        "api": NaverPlugin,
        "apiName": "nminseo",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Jiwon": {
        "api": NaverPlugin,
        "apiName": "njiwon",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Bora": {
        "api": NaverPlugin,
        "apiName": "nbora",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Jonghyun": {
        "api": NaverPlugin,
        "apiName": "njonghyun",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Joonyoung": {
        "api": NaverPlugin,
        "apiName": "njoonyoung",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Jaewook": {
        "api": NaverPlugin,
        "apiName": "njaewook",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Hyeri": {
        "api": NaverPlugin,
        "apiName": "nes_c_hyeri",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Sohyun": {
        "api": NaverPlugin,
        "apiName": "nes_c_sohyun",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Mikyung": {
        "api": NaverPlugin,
        "apiName": "nes_c_mikyung",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Kihyo": {
        "api": NaverPlugin,
        "apiName": "nes_c_kihyo",
        "languageName": "Korean",
        "gender": "Male",
        "languageCode": "ko",
    },
    "Sally": {
        "api": MaryTTSPlugin,
        "apiName": "cmu-slt-hsmm",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Henry": {
        "api": MaryTTSPlugin,
        "apiName": "cmu-rms-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Mark": {
        "api": MaryTTSPlugin,
        "apiName": "cmu-bdl-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Pierre": {
        "api": MaryTTSPlugin,
        "apiName": "upmc-pierre-hsmm",
        "languageName": "French",
        "gender": "Male",
        "languageCode": "fr-FR",
    },
    "Jessica": {
        "api": MaryTTSPlugin,
        "apiName": "upmc-jessica-hsmm",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Lucia": {
        "api": MaryTTSPlugin,
        "apiName": "istc-lucia-hsmm",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it",
    },
    "Hans": {
        "api": MaryTTSPlugin,
        "apiName": "dfki-pavoque-neutral-hsmm",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de-DE",
    },
    "Roberto": {
        "api": MaryTTSPlugin,
        "apiName": "mivoq-roberto-hsmm",
        "languageName": "Itallian",
        "gender": "Male",
        "languageCode": "it",
    },
    "Patrizia": {
        "api": MaryTTSPlugin,
        "apiName": "mivoq-patrizia-hsmm",
        "languageName": "Itallian",
        "gender": "Female",
        "languageCode": "it",
    },
    "Piero": {
        "api": MaryTTSPlugin,
        "apiName": "istc-piero-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Camila": {
        "api": MaryTTSPlugin,
        "apiName": "enst-camilla-hsmm",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr",
    },
    "Stefan": {
        "api": MaryTTSPlugin,
        "apiName": "dfki-stefan-hsmm",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de",
    },
    "Mario": {
        "api": MaryTTSPlugin,
        "apiName": "istc-speaker_internazionale-hsmm",
        "languageName": "Italian",
        "gender": "Male",
        "languageCode": "it",
    },
    "Shane": {
        "api": MaryTTSPlugin,
        "apiName": "cmu-jmk-hsmm",
        "languageName": "English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Aileen": {
        "api": MaryTTSPlugin,
        "apiName": "cmu-clb-hsmm",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Sophia": {
        "api": NanoTTSPlugin,
        "apiName": "en-GB",
        "languageName": "English (British)",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Isabella": {
        "api": NanoTTSPlugin,
        "apiName": "en-US",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Gisela": {
        "api": NanoTTSPlugin,
        "apiName": "de-DE",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Gabriela": {
        "api": NanoTTSPlugin,
        "apiName": "es-ES",
        "languageName": "Spanish",
        "gender": "Female",
        "languageCode": "es-ES",
    },
    "Coraline": {
        "api": NanoTTSPlugin,
        "apiName": "fr-FR",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Mia": {
        "api": NanoTTSPlugin,
        "apiName": "it-IT",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it-IT",
    },
    "Filiz": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Filiz",
        "languageName": "Turkish",
        "gender": "Female",
        "languageCode": "tr-TR",
    },
    "Astrid": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Astrid",
        "languageName": "Swedish",
        "gender": "Female",
        "languageCode": "sv-SE",
    },
    "Tatyana": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Tatyana",
        "languageName": "Russian",
        "gender": "Female",
        "languageCode": "ru-RU",
    },
    "Maxim": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Maxim",
        "languageName": "Russian",
        "gender": "Male",
        "languageCode": "ru-RU",
    },
    "Elena": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Carmen",
        "languageName": "Romanian",
        "gender": "Female",
        "languageCode": "ro-RO",
    },
    "Inês": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Ines",
        "languageName": "Portuguese",
        "gender": "Female",
        "languageCode": "pt-PT",
    },
    "Cristiano": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Cristiano",
        "languageName": "Portuguese",
        "gender": "Male",
        "languageCode": "pt-PT",
    },
    "Vitória": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Vitoria",
        "languageName": "Brazilian Portuguese",
        "gender": "Female",
        "languageCode": "pt-BR",
    },
    "Ricardo": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Ricardo",
        "languageName": "Brazilian Portuguese",
        "gender": "Male",
        "languageCode": "pt-BR",
    },
    "Maja": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Maja",
        "languageName": "Polish",
        "gender": "Female",
        "languageCode": "pl-PL",
    },
    "Jan": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Jan",
        "languageName": "Polish",
        "gender": "Male",
        "languageCode": "pl-PL",
    },
    "Jacek": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Jacek",
        "languageName": "Polish",
        "gender": "Male",
        "languageCode": "pl-PL",
    },
    "Ewa": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Ewa",
        "languageName": "Polish",
        "gender": "Female",
        "languageCode": "pl-PL",
    },
    "Ruben": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Ruben",
        "languageName": "Dutch",
        "gender": "Male",
        "languageCode": "nl-NL",
    },
    "Lotte": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nl-NL-Wavenet-E",
        "languageName": "Dutch",
        "gender": "Female",
        "languageCode": "nl-NL",
    },
    "Liv": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Liv",
        "languageName": "Norwegian",
        "gender": "Female",
        "languageCode": "nb-NO",
    },
    "Seoyeon": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Seoyeon",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko-KR",
    },
    "Takumi": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Takumi",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja-JP",
    },
    "Mizuki": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Mizuki",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja-JP",
    },
    "Giorgio": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Giorgio",
        "languageName": "Italian",
        "gender": "Male",
        "languageCode": "it-IT",
    },
    "Carla": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Carla",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it-IT",
    },
    "Bianca": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Bianca",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it-IT",
    },
    "Karl": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Karl",
        "languageName": "Icelandic",
        "gender": "Male",
        "languageCode": "is-IS",
    },
    "Dóra": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Dora",
        "languageName": "Icelandic",
        "gender": "Female",
        "languageCode": "is-IS",
    },
    "Mathieu": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Mathieu",
        "languageName": "French",
        "gender": "Male",
        "languageCode": "fr-FR",
    },
    "Céline": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Celine",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Chantal": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Chantal",
        "languageName": "Canadian French",
        "gender": "Female",
        "languageCode": "fr-CA",
    },
    "Penélope": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Penelope",
        "languageName": "US Spanish",
        "gender": "Female",
        "languageCode": "es-US",
    },
    "Miguel": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Miguel",
        "languageName": "US Spanish",
        "gender": "Male",
        "languageCode": "es-US",
    },
    "Rosa": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Mia",
        "languageName": "Mexican, Spanish",
        "gender": "Female",
        "languageCode": "es-MX",
    },
    "Enrique": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "es-ES_EnriqueVoice",
        "languageName": "Spanish",
        "gender": "Male",
        "languageCode": "es-ES",
    },
    "Conchita": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Conchita",
        "languageName": "Castilian Spanish",
        "gender": "Female",
        "languageCode": "es-ES",
    },
    "Geraint": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Geraint",
        "languageName": "Welsh English",
        "gender": "Male",
        "languageCode": "en-GB-WLS",
    },
    "Salli": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Salli",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Matthew": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Matthew",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Kimberly": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Kimberly",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Kendra": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Kendra",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Justin": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Justin",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Benjamin": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Joey",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Joanna": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Joanna",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Ivy": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Ivy",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Raveena": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Raveena",
        "languageName": "Indian English",
        "gender": "Female",
        "languageCode": "en-IN",
    },
    "Aditi": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Aditi",
        "languageName": "Indian English",
        "gender": "Female",
        "languageCode": "en-IN",
    },
    "Emma": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Emma",
        "languageName": "British English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Brian": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Brian",
        "languageName": "British English",
        "gender": "Male",
        "languageCode": "en-GB",
    },
    "Amy": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Amy",
        "languageName": "British English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Russell": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Russell",
        "languageName": "Australian English",
        "gender": "Male",
        "languageCode": "en-AU",
    },
    "Nicole": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Nicole",
        "languageName": "Australian English",
        "gender": "Female",
        "languageCode": "en-AU",
    },
    "Vicki": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Vicki",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Marlene": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Marlene",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Walter": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Hans",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de-DE",
    },
    "Naja": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Naja",
        "languageName": "Danish",
        "gender": "Female",
        "languageCode": "da-DK",
    },
    "Mads": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Mads",
        "languageName": "Danish",
        "gender": "Male",
        "languageCode": "da-DK",
    },
    "Gwyneth": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Gwyneth",
        "languageName": "Welsh",
        "gender": "Female",
        "languageCode": "cy-GB",
    },
    "Zhiyu": {
        "api": StreamElementsPlugin,
        "apiExtra": "Polly",
        "apiName": "Zhiyu",
        "languageName": "Chinese, Mandarin",
        "gender": "Female",
        "languageCode": "cmn-CN",
    },
    "Sofia": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "es-US_SofiaVoice",
        "languageName": "American Spanish",
        "gender": "Female",
        "languageCode": "es-US",
    },
    "Isabela": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "pt-BR_IsabelaVoice",
        "languageName": "Brazilian Portuguese",
        "gender": "Female",
        "languageCode": "pt-BR",
    },
    "Michael": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Michael",
        "languageName": "German (Austria)",
        "gender": "Male",
        "languageCode": "de-AT",
    },
    "Emi": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "ja-JP_EmiVoice",
        "languageName": "Japanese (日本語)",
        "gender": "Female",
        "languageCode": "ja-JP",
    },
    "Allison": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "en-US_AllisonVoice",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Renee": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "fr-FR_ReneeVoice",
        "languageName": "French (français)",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Francesca": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "it-IT_FrancescaVoice",
        "languageName": "Italian (italiano)",
        "gender": "Female",
        "languageCode": "it-IT",
    },
    "Laura": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "es-ES_LauraVoice",
        "languageName": "Castilian Spanish (español castellano)",
        "gender": "Female",
        "languageCode": "es-ES",
    },
    "Birgit": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "de-DE_BirgitVoice",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Dieter": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "de-DE_DieterVoice",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de-DE",
    },
    "Lisa": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "en-US_LisaVoice",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Kate": {
        "api": StreamElementsPlugin,
        "apiExtra": "Watson",
        "apiName": "en-GB_KateVoice",
        "languageName": "British English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Rosalinda": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "es-ES-Standard-A",
        "languageName": "Castilian Spanish",
        "gender": "Female",
        "languageCode": "es-ES",
    },
    "Gianna": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "it-IT-Standard-A",
        "languageName": "Italian (italiano)",
        "gender": "Female",
        "languageCode": "it-IT",
    },
    "Valentina": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "it-IT-Wavenet-A",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it-IT",
    },
    "Koharu": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ja-JP-Standard-A",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja-JP",
    },
    "Miho": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ja-JP-Wavenet-A",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja-JP",
    },
    "Heosu": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ko-KR-Standard-A",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko-KR",
    },
    "Grace": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ko-KR-Wavenet-A",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko-KR",
    },
    "Alice": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pt-BR-Standard-A",
        "languageName": "Brazilian Portuguese",
        "gender": "Female",
        "languageCode": "pt-BR",
    },
    "Zehra": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "tr-TR-Standard-A",
        "languageName": "Turkish",
        "gender": "Female",
        "languageCode": "tr-TR",
    },
    "Elsa": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "sv-SE-Standard-A",
        "languageName": "Swedish",
        "gender": "Female",
        "languageCode": "sv-SE",
    },
    "Annemieke": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nl-NL-Standard-A",
        "languageName": "Dutch",
        "gender": "Female",
        "languageCode": "nl-NL",
    },
    "Eva": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nl-NL-Wavenet-A",
        "languageName": "Dutch",
        "gender": "Female",
        "languageCode": "nl-NL",
    },
    "Carter": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Wavenet-A",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Paul": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Wavenet-B",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Evelyn": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Wavenet-C",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Liam": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Wavenet-D",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Jasmine": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Wavenet-E",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Madison": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Wavenet-F",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Layla": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Standard-A",
        "languageName": "British English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Ali": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Standard-B",
        "languageName": "British English",
        "gender": "Male",
        "languageCode": "en-GB",
    },
    "Scarlett": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Standard-C",
        "languageName": "British English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Oliver": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Standard-D",
        "languageName": "British English",
        "gender": "Male",
        "languageCode": "en-GB",
    },
    "Bella": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Wavenet-A",
        "languageName": "British English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "John": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Wavenet-B",
        "languageName": "British English",
        "gender": "Male",
        "languageCode": "en-GB",
    },
    "Victoria": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Wavenet-C",
        "languageName": "British English",
        "gender": "Female",
        "languageCode": "en-GB",
    },
    "Ron": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-GB-Wavenet-D",
        "languageName": "British English",
        "gender": "Male",
        "languageCode": "en-GB",
    },
    "Mark": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Standard-B",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Vanessa": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Standard-C",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Zachary": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Standard-D",
        "languageName": "US English",
        "gender": "Male",
        "languageCode": "en-US",
    },
    "Audrey": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-US-Standard-E",
        "languageName": "US English",
        "gender": "Female",
        "languageCode": "en-US",
    },
    "Karolina": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "de-DE-Standard-A",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Albert": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "de-DE-Standard-B",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de-DE",
    },
    "Angelika": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "de-DE-Wavenet-A",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Oskar": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "de-DE-Wavenet-B",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de-DE",
    },
    "Nina": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "de-DE-Wavenet-C",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de-DE",
    },
    "Sebastian": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "de-DE-Wavenet-D",
        "languageName": "German",
        "gender": "Male",
        "languageCode": "de-DE",
    },
    "Zoe": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Standard-A",
        "languageName": "Australian English",
        "gender": "Female",
        "languageCode": "en-AU",
    },
    "Luke": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Standard-B",
        "languageName": "Australian English",
        "gender": "Male",
        "languageCode": "en-AU",
    },
    "Samantha": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Wavenet-A",
        "languageName": "Australian English",
        "gender": "Female",
        "languageCode": "en-AU",
    },
    "Steve": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Wavenet-B",
        "languageName": "Australian English",
        "gender": "Male",
        "languageCode": "en-AU",
    },
    "Courtney": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Wavenet-C",
        "languageName": "Australian English",
        "gender": "Female",
        "languageCode": "en-AU",
    },
    "Jayden": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Wavenet-D",
        "languageName": "Australian English",
        "gender": "Male",
        "languageCode": "en-AU",
    },
    "Ashleigh": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Standard-C",
        "languageName": "Australian English",
        "gender": "Female",
        "languageCode": "en-AU",
    },
    "Daniel": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-AU-Standard-D",
        "languageName": "Australian English",
        "gender": "Male",
        "languageCode": "en-AU",
    },
    "Juliette": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-CA-Standard-A",
        "languageName": "Canadian French",
        "gender": "Female",
        "languageCode": "fr-CA",
    },
    "Felix": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-CA-Standard-B",
        "languageName": "Canadian French",
        "gender": "Male",
        "languageCode": "fr-CA",
    },
    "Camille": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-CA-Standard-C",
        "languageName": "Canadian French",
        "gender": "Female",
        "languageCode": "fr-CA",
    },
    "Jacques": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-CA-Standard-D",
        "languageName": "Canadian French",
        "gender": "Male",
        "languageCode": "fr-CA",
    },
    "Yvonne": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-FR-Standard-C",
        "languageName": "French (français)",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Gaspard": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-FR-Standard-D",
        "languageName": "French (français)",
        "gender": "Male",
        "languageCode": "fr-FR",
    },
    "Emilie": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-FR-Wavenet-A",
        "languageName": "French (français)",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Marcel": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-FR-Wavenet-B",
        "languageName": "French (français)",
        "gender": "Male",
        "languageCode": "fr-FR",
    },
    "Brigitte": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-FR-Wavenet-C",
        "languageName": "French (français)",
        "gender": "Female",
        "languageCode": "fr-FR",
    },
    "Simon": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fr-FR-Wavenet-D",
        "languageName": "French (français)",
        "gender": "Male",
        "languageCode": "fr-FR",
    },
    "Marie": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "da-DK-Wavenet-A",
        "languageName": "Danish",
        "gender": "Female",
        "languageCode": "da-DK",
    },
    "Amelia": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pl-PL-Wavenet-A",
        "languageName": "Polish (Poland)",
        "gender": "Female",
        "languageCode": "pl-PL",
    },
    "Stanislaw": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pl-PL-Wavenet-B",
        "languageName": "Polish (Poland)",
        "gender": "Male",
        "languageCode": "pl-PL",
    },
    "Tomasz": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pl-PL-Wavenet-C",
        "languageName": "Polish (Poland)",
        "gender": "Male",
        "languageCode": "pl-PL",
    },
    "Klaudia": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pl-PL-Wavenet-D",
        "languageName": "Polish (Poland)",
        "gender": "Female",
        "languageCode": "pl-PL",
    },
    "Beatriz": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pt-PT-Wavenet-A",
        "languageName": "Portuguese (Portugal)",
        "gender": "Female",
        "languageCode": "pt-PT",
    },
    "Francisco": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pt-PT-Wavenet-B",
        "languageName": "Portuguese (Portugal)",
        "gender": "Male",
        "languageCode": "pt-PT",
    },
    "Lucas": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pt-PT-Wavenet-C",
        "languageName": "Portuguese (Portugal)",
        "gender": "Male",
        "languageCode": "pt-PT",
    },
    "Carolina": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "pt-PT-Wavenet-D",
        "languageName": "Portuguese (Portugal)",
        "gender": "Female",
        "languageCode": "pt-PT",
    },
    "Маша (Masha)": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ru-RU-Wavenet-A",
        "languageName": "Russian (Russia)",
        "gender": "Female",
        "languageCode": "ru-RU",
    },
    "Илья (Ilya)": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ru-RU-Wavenet-B",
        "languageName": "Russian (Russia)",
        "gender": "Male",
        "languageCode": "ru-RU",
    },
    "Алёна (Alena)": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ru-RU-Wavenet-C",
        "languageName": "Russian (Russia)",
        "gender": "Female",
        "languageCode": "ru-RU",
    },
    "Пётр (Petr)": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ru-RU-Wavenet-D",
        "languageName": "Russian (Russia)",
        "gender": "Male",
        "languageCode": "ru-RU",
    },
    "Eliska": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "sk-SK-Wavenet-A",
        "languageName": "Slovak (Slovakia)",
        "gender": "Female",
        "languageCode": "sk-SK",
    },
    "Yagmur": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "tr-TR-Wavenet-A",
        "languageName": "Turkish (Turkey)",
        "gender": "Female",
        "languageCode": "tr-TR",
    },
    "Mehmet": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "tr-TR-Wavenet-B",
        "languageName": "Turkish (Turkey)",
        "gender": "Male",
        "languageCode": "tr-TR",
    },
    "Miray": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "tr-TR-Wavenet-C",
        "languageName": "Turkish (Turkey)",
        "gender": "Female",
        "languageCode": "tr-TR",
    },
    "Elif": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "tr-TR-Wavenet-D",
        "languageName": "Turkish (Turkey)",
        "gender": "Female",
        "languageCode": "tr-TR",
    },
    "Enes": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "tr-TR-Wavenet-E",
        "languageName": "Turkish (Turkey)",
        "gender": "Male",
        "languageCode": "tr-TR",
    },
    "Vladislav": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "uk-UA-Wavenet-A",
        "languageName": "Ukrainian (Ukraine)",
        "gender": "Male",
        "languageCode": "uk-UA",
    },
    "Aisha": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ar-XA-Wavenet-A",
        "languageName": "Arabic",
        "gender": "Female",
        "languageCode": "ar-XA",
    },
    "Ahmad": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ar-XA-Wavenet-C",
        "languageName": "Arabic",
        "gender": "Male",
        "languageCode": "ar-XA",
    },
    "Silvia": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "cs-CZ-Wavenet-A",
        "languageName": "Czech",
        "gender": "Female",
        "languageCode": "cs-CZ",
    },
    "Lars": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nl-NL-Wavenet-B",
        "languageName": "Dutch",
        "gender": "Male",
        "languageCode": "nl-NL",
    },
    "Marc": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nl-NL-Wavenet-C",
        "languageName": "Dutch",
        "gender": "Male",
        "languageCode": "nl-NL",
    },
    "Verona": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nl-NL-Wavenet-D",
        "languageName": "Dutch",
        "gender": "Female",
        "languageCode": "nl-NL",
    },
    "Anushri": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-IN-Wavenet-A",
        "languageName": "English (India)",
        "gender": "Female",
        "languageCode": "en-IN",
    },
    "Sundar": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-IN-Wavenet-B",
        "languageName": "English (India)",
        "gender": "Male",
        "languageCode": "en-IN",
    },
    "Satya": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "en-IN-Wavenet-C",
        "languageName": "English (India)",
        "gender": "Male",
        "languageCode": "en-IN",
    },
    "Tala": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fil-PH-Wavenet-A",
        "languageName": "Filipino",
        "gender": "Female",
        "languageCode": "fil-PH",
    },
    "Marianne": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "fi-FI-Wavenet-A",
        "languageName": "Finnish",
        "gender": "Female",
        "languageCode": "fi-FI",
    },
    "Thalia": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "el-GR-Wavenet-A",
        "languageName": "Greek",
        "gender": "Female",
        "languageCode": "el-GR",
    },
    "Sneha": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "hi-IN-Wavenet-A",
        "languageName": "Hindi",
        "gender": "Female",
        "languageCode": "hi-IN",
    },
    "Arnav": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "hi-IN-Wavenet-B",
        "languageName": "Hindi",
        "gender": "Male",
        "languageCode": "hi-IN",
    },
    "Aadhav": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "hi-IN-Wavenet-C",
        "languageName": "Hindi",
        "gender": "Male",
        "languageCode": "hi-IN",
    },
    "Ishtevan ": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "hu-HU-Wavenet-A",
        "languageName": "Hungarian",
        "gender": "Female",
        "languageCode": "hu-HU",
    },
    "Anisa": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "id-ID-Wavenet-A",
        "languageName": "Indonesian",
        "gender": "Female",
        "languageCode": "id-ID",
    },
    "Budi": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "id-ID-Wavenet-B",
        "languageName": "Indonesian",
        "gender": "Male",
        "languageCode": "id-ID",
    },
    "Bayu": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "id-ID-Wavenet-C",
        "languageName": "Indonesian",
        "gender": "Male",
        "languageCode": "id-ID",
    },
    "Stella": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "it-IT-Wavenet-B",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it-IT",
    },
    "Alessandro": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "it-IT-Wavenet-C",
        "languageName": "Italian",
        "gender": "Male",
        "languageCode": "it-IT",
    },
    "Luca": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "it-IT-Wavenet-D",
        "languageName": "Italian",
        "gender": "Male",
        "languageCode": "it-IT",
    },
    "Eiko": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ja-JP-Wavenet-B",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja-JP",
    },
    "Haruto": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ja-JP-Wavenet-C",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja-JP",
    },
    "Eichi": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "ja-JP-Wavenet-D",
        "languageName": "Japanese",
        "gender": "Male",
        "languageCode": "ja-JP",
    },
    "Li Na": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "cmn-CN-Wavenet-A",
        "languageName": "Mandarin Chinese",
        "gender": "Female",
        "languageCode": "cmn-CN",
    },
    "Wang": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "cmn-CN-Wavenet-B",
        "languageName": "Mandarin Chinese",
        "gender": "Male",
        "languageCode": "cmn-CN",
    },
    "Bai": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "cmn-CN-Wavenet-C",
        "languageName": "Mandarin Chinese",
        "gender": "Male",
        "languageCode": "cmn-CN",
    },
    "Mingli": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "cmn-CN-Wavenet-D",
        "languageName": "Mandarin Chinese",
        "gender": "Female",
        "languageCode": "cmn-CN",
    },
    "Nora": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nb-no-Wavenet-E",
        "languageName": "Norwegian",
        "gender": "Female",
        "languageCode": "nb-no",
    },
    "Malena": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nb-no-Wavenet-A",
        "languageName": "Norwegian",
        "gender": "Female",
        "languageCode": "nb-no",
    },
    "Jacob": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nb-no-Wavenet-B",
        "languageName": "Norwegian",
        "gender": "Male",
        "languageCode": "nb-no",
    },
    "Thea": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nb-no-Wavenet-C",
        "languageName": "Norwegian",
        "gender": "Female",
        "languageCode": "nb-no",
    },
    "Aksel": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "nb-no-Wavenet-D",
        "languageName": "Norwegian",
        "gender": "Male",
        "languageCode": "nb-no",
    },
    "Linh": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "vi-VN-Wavenet-A",
        "languageName": "Vietnamese",
        "gender": "Female",
        "languageCode": "vi-VN",
    },
    "Nguyen": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "vi-VN-Wavenet-B",
        "languageName": "Vietnamese",
        "gender": "Male",
        "languageCode": "vi-VN",
    },
    "phuong": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "vi-VN-Wavenet-C",
        "languageName": "Vietnamese",
        "gender": "Female",
        "languageCode": "vi-VN",
    },
    "Viet": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "vi-VN-Wavenet-D",
        "languageName": "Vietnamese",
        "gender": "Male",
        "languageCode": "vi-VN",
    },
    "Aleksandra": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "sr-rs-Standard-A",
        "languageName": "Serbian",
        "gender": "Female",
        "languageCode": "sr-RS",
    },
    "Juris": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "lv-lv-Standard-A",
        "languageName": "Latvian",
        "gender": "Male",
        "languageCode": "lv-LV",
    },
    "Helga": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "is-is-Standard-A",
        "languageName": "Icelandic",
        "gender": "Female",
        "languageCode": "is-IS",
    },
    "Nikolina": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "bg-bg-Standard-A",
        "languageName": "Bulgarian",
        "gender": "Female",
        "languageCode": "bg-BG",
    },
    "Sonya": {
        "api": StreamElementsPlugin,
        "apiExtra": "GCP",
        "apiName": "af-ZA-Standard-A",
        "languageName": "Afrikaans (South Africa)",
        "gender": "Female",
        "languageCode": "af-ZA",
    },
    "Tracy": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Tracy",
        "languageName": "Hong Kong (traditional characters)",
        "gender": "Female",
        "languageCode": "zh-HK",
    },
    "Danny": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Danny",
        "languageName": "Hong Kong (traditional characters)",
        "gender": "Male",
        "languageCode": "zh-HK",
    },
    "Huihui": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Huihui",
        "languageName": "Chinese (simplified characters)",
        "gender": "Female",
        "languageCode": "zh-CN",
    },
    "Yaoyao": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Yaoyao",
        "languageName": "Chinese (simplified characters)",
        "gender": "Female",
        "languageCode": "zh-CN",
    },
    "Kangkang": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Kangkang",
        "languageName": "Chinese (simplified characters)",
        "gender": "Male",
        "languageCode": "zh-CN",
    },
    "HanHan": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "HanHan",
        "languageName": "Taiwanese (traditional characters)",
        "gender": "Female",
        "languageCode": "zh-TW",
    },
    "Zhiwei": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Zhiwei",
        "languageName": "Taiwanese (traditional characters)",
        "gender": "Male",
        "languageCode": "zh-TW",
    },
    "Doron": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Asaf",
        "languageName": "Hebrew",
        "gender": "Male",
        "languageCode": "he-IL",
    },
    "An": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "An",
        "languageName": "Vietnamese",
        "gender": "Male",
        "languageCode": "vi-VN",
    },
    "Stefanos": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Stefanos",
        "languageName": "Greek",
        "gender": "Male",
        "languageCode": "el-GR",
    },
    "Filip": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Filip",
        "languageName": "Slovak",
        "gender": "Male",
        "languageCode": "sk-SK",
    },
    "Ivan": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Ivan",
        "languageName": "Bulgarian",
        "gender": "Male",
        "languageCode": "bg-BG",
    },
    "Heidi": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Heidi",
        "languageName": "Finnish",
        "gender": "Female",
        "languageCode": "fi-FI",
    },
    "Herena": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Herena",
        "languageName": "Catalan (Spain)",
        "gender": "Female",
        "languageCode": "ca-ES",
    },
    "Kalpana": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Kalpana",
        "languageName": "Hindi (India)",
        "gender": "Female",
        "languageCode": "hi-IN",
    },
    "Hemant": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Hemant",
        "languageName": "Hindi (India)",
        "gender": "Male",
        "languageCode": "hi-IN",
    },
    "Matej": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Matej",
        "languageName": "Croatian",
        "gender": "Male",
        "languageCode": "hr-HR",
    },
    "Andika": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Andika",
        "languageName": "Indonesian",
        "gender": "Male",
        "languageCode": "id-ID",
    },
    "Rizwan": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Rizwan",
        "languageName": "Malay",
        "gender": "Male",
        "languageCode": "ms-MY",
    },
    "Lado": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Lado",
        "languageName": "Slovenian",
        "gender": "Male",
        "languageCode": "sl-SI",
    },
    "Valluvar": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Valluvar",
        "languageName": "Tamil (India)",
        "gender": "Male",
        "languageCode": "ta-IN",
    },
    "Linda": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Linda",
        "languageName": "English (Canada)",
        "gender": "Female",
        "languageCode": "en-CA",
    },
    "Heather": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Heather",
        "languageName": "English (Canada)",
        "gender": "Female",
        "languageCode": "en-CA",
    },
    "Sean": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Sean",
        "languageName": "English (Ireland)",
        "gender": "Male",
        "languageCode": "en-IE",
    },
    "Karsten": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Karsten",
        "languageName": "German (Switzerland)",
        "gender": "Male",
        "languageCode": "de-CH",
    },
    "Guillaume": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Guillaume",
        "languageName": "French (Switzerland)",
        "gender": "Male",
        "languageCode": "fr-CH",
    },
    "Pattara": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Pattara",
        "languageName": "Thai",
        "gender": "Male",
        "languageCode": "th-TH",
    },
    "Jakub": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Jakub",
        "languageName": "Czech",
        "gender": "Male",
        "languageCode": "cs-CZ",
    },
    "Szabolcs": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Szabolcs",
        "languageName": "Hungarian",
        "gender": "Male",
        "languageCode": "hu-HU",
    },
    "Hoda": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Hoda",
        "languageName": "Arabic (Egypt)",
        "gender": "Female",
        "languageCode": "ar-EG",
    },
    "Naayf": {
        "api": StreamElementsPlugin,
        "apiExtra": "Azure",
        "apiName": "Naayf",
        "languageName": "Arabic (Saudi Arabia)",
        "gender": "Male",
        "languageCode": "ar-SA",
    },
    "Abina": {
        "api": GoogleTranslatePlugin,
        "apiName": "af",
        "languageName": "Afrikaans",
        "gender": "Female",
        "languageCode": "af",
    },
    "Akilah": {
        "api": GoogleTranslatePlugin,
        "apiName": "ar",
        "languageName": "Arabic",
        "gender": "Female",
        "languageCode": "ar",
    },
    "Bilyana": {
        "api": GoogleTranslatePlugin,
        "apiName": "bg",
        "languageName": "Bulgarian",
        "gender": "Female",
        "languageCode": "bg",
    },
    "Akil": {
        "api": GoogleTranslatePlugin,
        "apiName": "bn",
        "languageName": "Bengali",
        "gender": "Female",
        "languageCode": "bn",
    },
    "Lejla": {
        "api": GoogleTranslatePlugin,
        "apiName": "bs",
        "languageName": "Bosnian",
        "gender": "Female",
        "languageCode": "bs",
    },
    "Marta": {
        "api": GoogleTranslatePlugin,
        "apiName": "ca",
        "languageName": "Catalan",
        "gender": "Female",
        "languageCode": "ca",
    },
    "Tereza": {
        "api": GoogleTranslatePlugin,
        "apiName": "cs",
        "languageName": "Czech",
        "gender": "Female",
        "languageCode": "cs",
    },
    "Efa": {
        "api": GoogleTranslatePlugin,
        "apiName": "cy",
        "languageName": "Welsh",
        "gender": "Female",
        "languageCode": "cy",
    },
    "Freja": {
        "api": GoogleTranslatePlugin,
        "apiName": "da",
        "languageName": "Danish",
        "gender": "Female",
        "languageCode": "da",
    },
    "Christina": {
        "api": GoogleTranslatePlugin,
        "apiName": "de",
        "languageName": "German",
        "gender": "Female",
        "languageCode": "de",
    },
    "Athena": {
        "api": GoogleTranslatePlugin,
        "apiName": "el",
        "languageName": "Greek",
        "gender": "Female",
        "languageCode": "el",
    },
    "Olivia": {
        "api": GoogleTranslatePlugin,
        "apiName": "en",
        "languageName": "English",
        "gender": "Female",
        "languageCode": "en",
    },
    "Susano": {
        "api": GoogleTranslatePlugin,
        "apiName": "eo",
        "languageName": "Esperanto",
        "gender": "Female",
        "languageCode": "eo",
    },
    "Julieta": {
        "api": GoogleTranslatePlugin,
        "apiName": "es",
        "languageName": "Spanish",
        "gender": "Female",
        "languageCode": "es",
    },
    "Dorel": {
        "api": GoogleTranslatePlugin,
        "apiName": "et",
        "languageName": "Estonian",
        "gender": "Female",
        "languageCode": "et",
    },
    "Kaarina": {
        "api": GoogleTranslatePlugin,
        "apiName": "fi",
        "languageName": "Finnish",
        "gender": "Female",
        "languageCode": "fi",
    },
    "Esme": {
        "api": GoogleTranslatePlugin,
        "apiName": "fr",
        "languageName": "French",
        "gender": "Female",
        "languageCode": "fr",
    },
    "Iditri": {
        "api": GoogleTranslatePlugin,
        "apiName": "gu",
        "languageName": "Gujarati",
        "gender": "Female",
        "languageCode": "gu",
    },
    "Advika": {
        "api": GoogleTranslatePlugin,
        "apiName": "hi",
        "languageName": "Hindi",
        "gender": "Female",
        "languageCode": "hi",
    },
    "Ema": {
        "api": GoogleTranslatePlugin,
        "apiName": "hr",
        "languageName": "Croatian",
        "gender": "Female",
        "languageCode": "hr",
    },
    "Caitlin": {
        "api": GoogleTranslatePlugin,
        "apiName": "hu",
        "languageName": "Hungarian",
        "gender": "Female",
        "languageCode": "hu",
    },
    "Arax": {
        "api": GoogleTranslatePlugin,
        "apiName": "hy",
        "languageName": "Armenian",
        "gender": "Female",
        "languageCode": "hy",
    },
    "Rimba": {
        "api": GoogleTranslatePlugin,
        "apiName": "id",
        "languageName": "Indonesian",
        "gender": "Female",
        "languageCode": "id",
    },
    "Sigrun": {
        "api": GoogleTranslatePlugin,
        "apiName": "is",
        "languageName": "Icelandic",
        "gender": "Female",
        "languageCode": "is",
    },
    "Giana": {
        "api": GoogleTranslatePlugin,
        "apiName": "it",
        "languageName": "Italian",
        "gender": "Female",
        "languageCode": "it",
    },
    "Ichika": {
        "api": GoogleTranslatePlugin,
        "apiName": "ja",
        "languageName": "Japanese",
        "gender": "Female",
        "languageCode": "ja",
    },
    "Riyanto": {
        "api": GoogleTranslatePlugin,
        "apiName": "jw",
        "languageName": "Javanese",
        "gender": "Female",
        "languageCode": "jw",
    },
    "Chantou": {
        "api": GoogleTranslatePlugin,
        "apiName": "km",
        "languageName": "Khmer",
        "gender": "Female",
        "languageCode": "km",
    },
    "Zhanvi": {
        "api": GoogleTranslatePlugin,
        "apiName": "kn",
        "languageName": "Kannada",
        "gender": "Female",
        "languageCode": "kn",
    },
    "Si-Woo": {
        "api": GoogleTranslatePlugin,
        "apiName": "ko",
        "languageName": "Korean",
        "gender": "Female",
        "languageCode": "ko",
    },
    "Margarita": {
        "api": GoogleTranslatePlugin,
        "apiName": "la",
        "languageName": "Latin",
        "gender": "Female",
        "languageCode": "la",
    },
    "Elizabete": {
        "api": GoogleTranslatePlugin,
        "apiName": "lv",
        "languageName": "Latvian",
        "gender": "Female",
        "languageCode": "lv",
    },
    "Smaragda": {
        "api": GoogleTranslatePlugin,
        "apiName": "mk",
        "languageName": "Macedonian",
        "gender": "Female",
        "languageCode": "mk",
    },
    "Cik": {
        "api": GoogleTranslatePlugin,
        "apiName": "ms",
        "languageName": "Malay",
        "gender": "Female",
        "languageCode": "ms",
    },
    "Abhilasha": {
        "api": GoogleTranslatePlugin,
        "apiName": "ml",
        "languageName": "Malayalam",
        "gender": "Female",
        "languageCode": "ml",
    },
    "Aarzoo": {
        "api": GoogleTranslatePlugin,
        "apiName": "mr",
        "languageName": "Marathi",
        "gender": "Female",
        "languageCode": "mr",
    },
    "Hayma": {
        "api": GoogleTranslatePlugin,
        "apiName": "my",
        "languageName": "Myanmar (Burmese)",
        "gender": "Female",
        "languageCode": "my",
    },
    "Ditya": {
        "api": GoogleTranslatePlugin,
        "apiName": "ne",
        "languageName": "Nepali",
        "gender": "Female",
        "languageCode": "ne",
    },
    "Annemie": {
        "api": GoogleTranslatePlugin,
        "apiName": "nl",
        "languageName": "Dutch",
        "gender": "Female",
        "languageCode": "nl",
    },
    "Ingunn": {
        "api": GoogleTranslatePlugin,
        "apiName": "no",
        "languageName": "Norwegian",
        "gender": "Female",
        "languageCode": "no",
    },
    "Magdalena": {
        "api": GoogleTranslatePlugin,
        "apiName": "pl",
        "languageName": "Polish",
        "gender": "Female",
        "languageCode": "pl",
    },
    "Antonieta": {
        "api": GoogleTranslatePlugin,
        "apiName": "pt",
        "languageName": "Portuguese",
        "gender": "Female",
        "languageCode": "pt",
    },
    "Adelina": {
        "api": GoogleTranslatePlugin,
        "apiName": "ro",
        "languageName": "Romanian",
        "gender": "Female",
        "languageCode": "ro",
    },
    "Varvara": {
        "api": GoogleTranslatePlugin,
        "apiName": "ru",
        "languageName": "Russian",
        "gender": "Female",
        "languageCode": "ru",
    },
    "Amanthi": {
        "api": GoogleTranslatePlugin,
        "apiName": "si",
        "languageName": "Sinhala",
        "gender": "Female",
        "languageCode": "si",
    },
    "Branislava": {
        "api": GoogleTranslatePlugin,
        "apiName": "sk",
        "languageName": "Slovak",
        "gender": "Female",
        "languageCode": "sk",
    },
    "Agnesa": {
        "api": GoogleTranslatePlugin,
        "apiName": "sq",
        "languageName": "Albanian",
        "gender": "Female",
        "languageCode": "sq",
    },
    "Malina": {
        "api": GoogleTranslatePlugin,
        "apiName": "sr",
        "languageName": "Serbian",
        "gender": "Female",
        "languageCode": "sr",
    },
    "Aarifa": {
        "api": GoogleTranslatePlugin,
        "apiName": "su",
        "languageName": "Sundanese",
        "gender": "Female",
        "languageCode": "su",
    },
    "Karin": {
        "api": GoogleTranslatePlugin,
        "apiName": "sv",
        "languageName": "Swedish",
        "gender": "Female",
        "languageCode": "sv",
    },
    "Jabari": {
        "api": GoogleTranslatePlugin,
        "apiName": "sw",
        "languageName": "Swahili",
        "gender": "Female",
        "languageCode": "sw",
    },
    "Dharini": {
        "api": GoogleTranslatePlugin,
        "apiName": "ta",
        "languageName": "Tamil",
        "gender": "Female",
        "languageCode": "ta",
    },
    "Aaghnya": {
        "api": GoogleTranslatePlugin,
        "apiName": "te",
        "languageName": "Telugu",
        "gender": "Female",
        "languageCode": "te",
    },
    "Hathai": {
        "api": GoogleTranslatePlugin,
        "apiName": "th",
        "languageName": "Thai",
        "gender": "Female",
        "languageCode": "th",
    },
    "Luwalhati": {
        "api": GoogleTranslatePlugin,
        "apiName": "tl",
        "languageName": "Filipino",
        "gender": "Female",
        "languageCode": "tl",
    },
    "Defne": {
        "api": GoogleTranslatePlugin,
        "apiName": "tr",
        "languageName": "Turkish",
        "gender": "Female",
        "languageCode": "tr",
    },
    "Ruslana": {
        "api": GoogleTranslatePlugin,
        "apiName": "uk",
        "languageName": "Ukrainian",
        "gender": "Female",
        "languageCode": "uk",
    },
    "Tazmeen": {
        "api": GoogleTranslatePlugin,
        "apiName": "ur",
        "languageName": "Urdu",
        "gender": "Female",
        "languageCode": "ur",
    },
    "Huong": {
        "api": GoogleTranslatePlugin,
        "apiName": "vi",
        "languageName": "Vietnamese",
        "gender": "Female",
        "languageCode": "vi",
    },
    "Baozhai": {
        "api": GoogleTranslatePlugin,
        "apiName": "zh-CN",
        "languageName": "Chinese",
        "gender": "Female",
        "languageCode": "zh-CN",
    }
}
