voices = {
    "Anna": {
        "api_name": "danna",
        "languageName": "English",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "en",
    },
    "Clara": {
        "api_name": "clara",
        "languageName": "English",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "en",
    },
    "Matt": {
        "api_name": "matt",
        "languageName": "English",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "en",
    },
    "Joey": {
        "api_name": "djoey",
        "languageName": "English",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "en",
    },
    "Jose": {
        "api_name": "jose",
        "languageName": "Spanish",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "es",
    },
    "Carmen": {
        "api_name": "carmen",
        "languageName": "Spanish",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "es",
    },
    "Shinji": {
        "api_name": "shinji",
        "languageName": "Japanese",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Tomoko": {
        "api_name": "ntomoko",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Naomi": {
        "api_name": "nnaomi",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Hina": {
        "api_name": "dnaomi_joyful",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Yua": {
        "api_name": "dnaomi_formal",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Sayuri": {
        "api_name": "nsayuri",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Riko": {
        "api_name": "driko",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Eriko": {
        "api_name": "deriko",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Meimei": {
        "api_name": "meimei",
        "languageName": "Chinese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "zh",
    },
    "Liangliang": {
        "api_name": "liangliang",
        "languageName": "Chinese",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "zh",
    },
    "Chiahua": {
        "api_name": "chiahua",
        "languageName": "Taiwanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "zh",
    },
    "Kuanlin": {
        "api_name": "kuanlin",
        "languageName": "Taiwanese",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "zh",
    },
    "Hajime": {
        "api_name": "dhajime",
        "languageName": "Japanese",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Daiki": {
        "api_name": "ddaiki",
        "languageName": "Japanese",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Ayumu": {
        "api_name": "dayumu",
        "languageName": "Japanese",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Mio": {
        "api_name": "dmio",
        "languageName": "Japanese",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ja",
    },
    "Nara": {
        "api_name": "nara",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Mijin": {
        "api_name": "mijin",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Jinho": {
        "api_name": "njinho",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Minsang": {
        "api_name": "nminsang",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Hajoon": {
        "api_name": "nhajun",
        "languageName": "Korean",
        "gender": "Boy",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Dain": {
        "api_name": "ndain",
        "languageName": "Korean",
        "gender": "Girl",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Jiyoon": {
        "api_name": "njiyun",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Sujin": {
        "api_name": "nsujin",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Shinwoo": {
        "api_name": "nsinu",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Jihoon": {
        "api_name": "njihun",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Koeun": {
        "api_name": "ngoeun",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Eunyoung": {
        "api_name": "neunyoung",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Sunkyung": {
        "api_name": "nsunkyung",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Yujin": {
        "api_name": "nyujin",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Taejin": {
        "api_name": "ntaejin",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Youngil": {
        "api_name": "nyoungil",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Seungpyo": {
        "api_name": "nseungpyo",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Wontak": {
        "api_name": "nwontak",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Ara": {
        "api_name": "dara_ang",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Sunhee": {
        "api_name": "nsunhee",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Minseo": {
        "api_name": "nminseo",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Jiwon": {
        "api_name": "njiwon",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Bora": {
        "api_name": "nbora",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Jonghyun": {
        "api_name": "njonghyun",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Joonyoung": {
        "api_name": "njoonyoung",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Jaewook": {
        "api_name": "njaewook",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Hyeri": {
        "api_name": "nes_c_hyeri",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Sohyun": {
        "api_name": "nes_c_sohyun",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Mikyung": {
        "api_name": "nes_c_mikyung",
        "languageName": "Korean",
        "gender": "Female",
        "limit": 1000,
        "languageCode": "ko",
    },
    "Kihyo": {
        "api_name": "nes_c_kihyo",
        "languageName": "Korean",
        "gender": "Male",
        "limit": 1000,
        "languageCode": "ko",
    },
}
